# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'Allok8' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Allok8
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'Allok8Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Allok8UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
